#ifndef __CONFIG_H__
#define __CONFIG_H__

#define WAIT_TICKS 2000

#define DIFSOBEL_DIFF_THRESHOLD 25
#define DIFSOBEL_SOBEL_THRESHOLD 0
#define DIFF_THRESHOLD 20
#define CENTER_MINIMUM_AVGDIFF 2
#define MOVEMENT_MINIMUM_AVGDIFF 0.2
#define RADIO_THRESHOLD 10
#define MAX_CENTER_CALIBRATIONS 10
#define MIN_CENTER_MOVEMENT 2
#define CENTER_LOST_FRAMES 40 

#define TARGET_FACTOR_X 0.25
#define TARGET_FACTOR_Y 0.25
#define TARGET_FACTOR_Z 0.25
#define TARGET_LOST_X 0.9
#define TARGET_LOST_Y 0.9
#define TARGET_LOST_Z 0.9

#define MINIMUM_AREA 40
#define MAXIMUM_AREA 240

#define MAX_COLOR_DIFFERENCE 25

#define MAX_COLOR_STEPS 6
#define COLOR_SEPARATION 25

#define AREA_MARGIN 80
#define MIN_MOVEMENT_AROUND_CENTER 0.02
#define MIN_MOVEMENT_FRAMES 20

#endif
